Improve CS.

diff --git a/bin/installer b/bin/installer
--- a/bin/installer
+++ b/bin/installer
@@ -1,42 +1,50 @@
 #!/bin/sh
-set -x
+set -ex
+
+# Check environment
 
 fail() {
-    echo $1 1>&2
-    echo "Usage: $0 [install|uninstall]" 1>&2
+    echo 1>&2 "$1"
+    echo 1>&2 "Usage: $(basename "$0") [install|uninstall]"
     exit 1
 }
 
-if [ $# -lt 1 ] ; then
+if [ "$#" -lt 1 ] ; then
     fail "Invalid number of arguments."
 fi
 
-if [ $(id -u) -ne 0 ] ; then
+if [ "$(id -u)" -ne 0 ] ; then
     fail "Impossible to prepare the system without root privileges."
 fi
 
-if [ $(uname) != "Linux" ] ; then
+if [ "$(uname)" != "Linux" ] ; then
     fail "Impossible to prepare another operating system than Linux."
 fi
 
-case $1 in
+# Run installer
+
+INSTALL_DIRECTORY="${INSTALL_DIRECTORY:-/usr/local/sbin}"
+
+case "$1" in
     install )
-        curl -sLo ${INSTALL_DIRECTORY:-/usr/local/sbin}/dumb-entrypoint "https://github.com/timonier/dumb-entrypoint/raw/master/src/dumb-entrypoint"
-        chmod +x ${INSTALL_DIRECTORY:-/usr/local/sbin}/dumb-entrypoint
+        curl --location --output "${INSTALL_DIRECTORY}/dumb-entrypoint" "https://github.com/timonier/dumb-entrypoint/raw/master/src/dumb-entrypoint"
+        chmod +x "${INSTALL_DIRECTORY}/dumb-entrypoint"
 
-        curl -sLo ${INSTALL_DIRECTORY:-/usr/local/sbin}/dumb-init "https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64"
-        chmod +x ${INSTALL_DIRECTORY:-/usr/local/sbin}/dumb-init
+        export $(curl "https://raw.githubusercontent.com/timonier/version-lister/release/generated/dumb-init/latest" | xargs)
+        curl --location --output "${INSTALL_DIRECTORY}/dumb-init" "https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_amd64"
+        chmod +x "${INSTALL_DIRECTORY}/dumb-init"
 
-        curl -sLo ${INSTALL_DIRECTORY:-/usr/local/sbin}/gosu "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64"
-        chmod +sx ${INSTALL_DIRECTORY:-/usr/local/sbin}/gosu
+        export $(curl "https://raw.githubusercontent.com/timonier/version-lister/release/generated/gosu/latest" | xargs)
+        curl --location --output "${INSTALL_DIRECTORY}/gosu" "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64"
+        chmod +sx "${INSTALL_DIRECTORY}/gosu"
     ;;
 
     uninstall )
-        rm -f ${INSTALL_DIRECTORY:-/usr/local/sbin}/dumb-entrypoint
-        rm -f ${INSTALL_DIRECTORY:-/usr/local/sbin}/dumb-init
-        rm -f ${INSTALL_DIRECTORY:-/usr/local/sbin}/gosu
+        rm -f "${INSTALL_DIRECTORY}/dumb-entrypoint"
+        rm -f "${INSTALL_DIRECTORY}/dumb-init"
+        rm -f "${INSTALL_DIRECTORY}/gosu"
     ;;
 
     * )
-        fail "Argument $1 is invalid."
+        fail "Argument \"$1\" is invalid."
 esac
